name: 2026S

channels:
  - conda-forge
  - defaults

dependencies:

  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - xgboost
  - jupyter
  - ipykernel
  - rdkit

  - pip:
      - torch
      - torch-geometric



