name: myenv

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - numpy<2.0
  - pandas
  - scikit-learn
  - pytorch
  - pytorch_geometric
  - rdkit
  - xgboost
  - ipykernel
  - ipywidgets
  - openpyxl
